<h1>Mon profil</h1>

<?php $this->add('breadcrumbs'); ?>
<!--<form>
    <fieldset>
        <legend>Informations générales</legend>
        <div class="line">
            <label>Nom</label>
            <input type="text" value="<?php echo $this->utilisateur->get("nom"); ?>" name="nom" class="form-controle form-oblig form-mix" />
        </div>

        <div class="line">
            <label>Prénom</label>
            <input type="text" value="<?php echo $this->utilisateur->get("prenom"); ?>" name="prenom" class="form-controle form-oblig form-mix" />
        </div>

        <div class="line">
            <label>Société</label>
            <input type="text" value="<?php echo $this->utilisateur->get("societe"); ?>" name="societe" class="form-controle form-oblig form-mix" />
        </div>

        <div class="line">
            <label>Email</label>
            <input type="text" value="<?php echo $this->utilisateur->get("email"); ?>" name="email" class="form-controle form-oblig form-mix" />
        </div>
        <div class="btn-a gradient-green cb fr"><a class="formajaxsubmit" href="#">Modfier vos informations générales</a></div>
    </fieldset>
</form>-->

<form method="post" action="back/user/changepassword.html">
    <fieldset>
        <legend>Modifier le mot de passe</legend>
        <div class="line">
            <label>Mot de passe actuel</label>
            <input type="password" value="" name="old_password" class="form-controle form-oblig form-mix" />
        </div>

        <div class="line">
            <label>Nouveau mot de passe</label>
            <input type="password" value="" name="new_password" class="form-controle form-oblig form-mix" />
        </div>

        <div class="line">
            <label>Confirmation du nouveau mot de passe</label>
            <input type="password" value="" name="new_password_c" class="form-controle form-oblig form-mix" />
        </div>

        <button class="btn btn-success btn-small formajaxsubmit" type="submit" style="margin-left: 218px;"><i class="icon-edit"></i> Mettre à jour votre mot de passe</button>
    </fieldset>




</form>