
<h2><?php echo $this->title; ?></h2>

<?php
    if (isset($this->message)) {
?>
  <p>
      <?php echo $this->message; ?>
  </p>
<?php
    }
?>

<?php
    if (isset($this->timeRemaining) && $this->timeRemaining) {
?>
<svg width="360" height="170">
    <!-- Symbol -->
    <symbol id="s-text">
            <text  id="remaining-time" text-anchor="middle" x="50%" y="95%" dy=".0em">
                    <?php echo $this->timeRemaining; ?>
            </text>
    </symbol>
    <!-- Duplicate symbols -->
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
</svg>
<p>
    secondes
</p>
<?php
    }
?>

<div class="sub">
  <p>
      <a class="btn" href="<?php echo $this->btn['href']; ?>"><?php echo $this->btn['content']; ?> </a>
  </p>
</div>





<?php // $this->add('error/error'); ?>
<script type="text/javascript">
// update the tag with id "countdown" every 1 second
    var remainingInterval = setInterval(function () {
        var currentSeconds = document.getElementById('remaining-time').innerHTML;
        var newSeconds = Math.max(currentSeconds - 1, 0);
        document.getElementById('remaining-time').innerHTML = newSeconds;
        if (newSeconds <= 0) {
            location.reload();
            clearInterval(remainingInterval);
        }
    }, 1000);
</script>