<h2><?php echo $this->title; ?></h2>

<?php
    if (isset($this->code) && $this->code) {
?>
<svg width="360" height="200">
    <!-- Symbol -->
    <symbol id="s-text">
            <text text-anchor="middle" x="50%" y="100%" dy=".0em">
                    <?php echo $this->code; ?>
            </text>
    </symbol>
    <!-- Duplicate symbols -->
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
    <use xlink:href="#s-text" class="animate-text"></use>
</svg>
<?php
    }
?>

<div class="sub">
<?php
    if (isset($this->message)) {
?>
  <p>
      <?php echo $this->message; ?>
  </p>
<?php
    }
?>
  <p>
      <a class="btn" href="<?php echo $this->btn['href']; ?>"><?php echo $this->btn['content']; ?> </a>
  </p>
</div>