<?php foreach ($this->files as $file) { ?>
                <tr class="<?php echo $file['utilise'] ? '' : 'filenotused'; ?>" id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a  class="previsu" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['poids']; ?></td>
                    <td><?php if (isset($file['width'])) echo $file['width']; ?></td>
                    <td><?php if (isset($file['height'])) echo $file['height']; ?></td>
                    <td><?php echo Slrfw\Format\DateTime::sqlTo(substr($file['date_crea'], 0, 10)); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td><?php echo $file['utilise'] ? 'Oui' : 'Non'; ?></td>
                    <td class="center">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="<?php echo $file['path']; ?>" class="btn btn-info previsu" title="Visualiser"><i class="icon-camera"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
<?php } ?>


