
        <div>
            <a href="#" class="btn btn-sm btn-success" id="pickfiles<?php echo $this->idFilesList; ?>"><i class="fa fa-folder-open"></i> Ajouter un fichier</a>
        </div>

        <table id="tableau<?php echo $this->idFilesList; ?>" class="display" style="width:100%;">
            <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Taille</th>
                    <th>Date / Heure</th>
                    <th style="width: 50px;">&nbsp;</th>
                </tr>
            </thead>

            <tbody id="foldercontent<?php echo $this->idFilesList; ?>">

<?php foreach ($this->files as $file) { ?>

                <tr id="fileid_<?php echo $file['id']; ?>">
                    <td>
                        <a target="_blank" class="exec-onclick-zoom" data-zoom-src="<?php echo $file['path']; ?>" href="<?php echo $file['path']; ?>" title="<?php echo $file['rewriting']; ?>">
                            <img class="<?php echo $file['class']; ?>" src="<?php echo $file['path_mini']; ?>" alt="<?php echo $file['rewriting']; ?>" />
                        </a>
                    </td>
                    <td><?php echo $file['poids']; ?></td>
                    <td><?php echo \Solire\Lib\Format\DateTime::sqlTo(substr($file['date_crea'], 0, 10)); ?><br /><?php echo substr($file['date_crea'], 11); ?></td>
                    <td class="center">
                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <a href="<?php echo $file['path']; ?>" data-zoom-src="<?php echo $file['path']; ?>" class="btn btn-info exec-onclick-zoom" title="Visualiser"><i class="fa fa-camera"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>

<?php } ?>

            </tbody>
        </table>
