<div data-amd="modules/page/listefichiers">
    <h1>Gestion des fichiers</h1>

    <?php $this->add('breadcrumbs'); ?>

    <div class="row">
        <div class="col-md-6">
            <a href="#" class="btn btn-sm btn-success" id="pickfiles" style="display: none;"><i class="icon-folder-open"></i> Ajouter un fichier</a>
            <div id="folders"></div>
        </div>
        <div class="col-md-6">
            <?php // echo $this->datatableRender; ?>
        </div>
    </div>
</div>