<style>
    #tableau td {
            overflow: hidden; /* this is what fixes the expansion */
            white-space: normal;
            word-wrap: break-word;
            max-width: 400px;


        }

        #tableau tr.filenotused td {
            color: #777777;
            font-style: italic;
        }

        #tableau_length select {
            width: auto;
            margin-bottom: 0px;
        }


        #tableau_wrapper input {
            height: auto;
            margin-bottom: 0px;
        }

        #tableau_wrapper .fg-toolbar.ui-corner-tl {
            border-radius: 6px 6px 0px 0px;
        }

        #tableau_wrapper .fg-toolbar.ui-corner-bl {
            border-radius: 0px 0px 6px 6px;
        }


        #tableau_wrapper .ui-widget-header {
            margin: 0;
            box-shadow: none;
            border: none;
            border-radius: 0px;


        }

        thead input { width: 100% }
        #tableau tfoot input.search_init, #tableau tfoot input.text_filter { font-size : 11px; }

        select.select_filter {max-width: 100px;font-size : 11px;}



        #tableau table { width: 100%;}

        #tableau table a { text-decoration: underline; }
        #tableau table tr  >  td { border: 0px;text-align: left;vertical-align: top;  }
        #tableau table tr  >  td:first-child {  padding-left: 50px;width: 100px;font-weight: bold;  }
        #tableau table  >  tbody {
            border-top: 0px dotted #333333;
        }
        #tableau table  >  tbody tr:hover {
            background-color: #4A9DD7;
            color: #FFF;
        }
        #tableau tbody tr.even, #tableau tbody tr.odd,
        #tableau tbody tr.even td a, #tableau tbody tr.odd td a{
            color: #000;

        }
        #tableau tbody tr.even:hover, #tableau > tbody tr.even td.highlighted {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tbody tr.even:hover > td >  a, #tableau > tbody tr.even td.highlighted > a {
            color: #FFF;
        }


        #tableau tbody tr.odd:hover, #tableau > tbody tr.odd td.highlighted {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tbody tr.odd:hover > td > a, #tableau > tbody tr.odd td.highlighted > a {
            color: #FFF;
        }


        #tableau tr.even:hover {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_1 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_2 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.even:hover > td.sorting_3 {
            background-color: #E2FF89;
            color: #FFF;
        }

        #tableau tr.odd:hover {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_1 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_2 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.odd:hover > td.sorting_3 {
            background-color: #117ECA;
            color: #FFF;
        }

        #tableau tr.filenotused:hover td {
            color: #FFF;
        }


    #tableau_wrapper select {
        margin-bottom: 0;
        width: auto;
    }


    ins.jstree-icon, .horizontal_scroller {
        float: left;
    }

</style>


<h1>Gestion des fichiers</h1>

<?php $this->add('breadcrumbs'); ?>

<div id="mmenu">
    <!--    <div id="currentruntime" style="font-size:10px; color:#a1a1a1; font-style:italic; padding: 3px;"></div>-->

    <div style="float:left; margin-right:10px;height: 20px;">

        <!--<a href="#" class="button vert" id="add_folder">
                                        <span class="vert">ajouter un dossier</span>
                                </a>-->

        <a href="#" class="btn btn-small btn-success" id="pickfiles" style="display: none;"><i class="icon-folder-open"></i> Ajouter un fichier</a>
    </div>



    <!--<div style="float: left; margin-right: 10px;">
            <a href="#" class="button vert" id="uploadfiles">
                    <span class="vert">charger les fichiers</span>
            </a>
    </div>-->
</div>
<div class="clear"></div>

<div id="folders" style="width: 200px; overflow: hidden; float: left"></div>

<div id="colright" style="min-height: 400px; float: left; width: 75%; margin-left: 20px;display: none;">


    <?php echo $this->datatableRender; ?>


</div>