                    <div data-amd="modules/page/affichegabarit,modules/helper/ajaxcall,modules/page/upload,modules/render/beforeloadpage,modules/helper/zoom">
                        <h1>Gestion des pages</h1>
<?php
    $this->add('breadcrumbs');
?>
                        <h2><?php echo ($this->pages[BACK_ID_VERSION]->getMeta() ? 'Modification de ' : 'Création de ') . strtolower($this->pages[BACK_ID_VERSION]->getGabarit()->getLabel()); ?></h2>
<?php
    if (count($this->versions) > 0) {
?>
                        <div>
<?php
        foreach ($this->versions as $id_version => $version) {
            $page = $this->pages[$id_version];
?>
                            <div class="btn-group">
                                    <a title="<?php echo ($this->pages[BACK_ID_VERSION]->getMeta() ? '' : 'Page en cours de création en version : ') . $version['nom']; ?>" class="openlang <?php echo $id_version == BACK_ID_VERSION ? '' : 'translucide'; ?> btn btn-default btn-sm">
                                        <?php if($this->pages[BACK_ID_VERSION]->getMeta()) { ?>
                                            <img src="public/default/back/img/flags/png/<?php echo strtolower($version['suf']); ?>.png" alt="<?php echo $version['nom']; ?>" />
                                        <?php } else { ?>
                                            <i class="fa fa-clock-o" alt="Page en cours de création en version <?php echo $version['nom']; ?>"></i>
                                        <?php } ?>

                                    </a>
<?php
            if ($page->getMeta("rewriting") != "") {
                if ($page->getMeta('rewriting') != ''
                    && ($this->utilisateur->get("niveau") == "solire"
                        || $page->getGabarit()->getMakeHidden() == 1
                        || $page->getMeta('visible') == 0
                    )
                ) {
                    if (($page->makeHidden && $page->getMeta('visible') == 1)
                        || ($page->makeVisible && $page->getMeta('visible') == 0)
                    ) {
?>
                                    <button
                                        class="btn btn-sm <?php echo ($page->getMeta('visible') > 0 ? 'btn-success' : 'btn-default') ?> visible-lang exec-onclick-ajax"
                                        data-url="back/page/visible.html"
                                        data-id="<?php echo $page->getMeta('id'); ?>"
                                        data-id_version="<?php echo $page->getMeta('id_version'); ?>"
                                        data-visible="<?php echo $page->getMeta('visible'); ?>"
                                        title="Rendre '<?php echo $page->getMeta('titre'); ?>' <?php echo ($page->getMeta('visible') > 0 ? 'invisible' : 'visible' ) ?> sur le site">

                                        <i class="fa <?php echo ($page->getMeta('visible') > 0 ? 'fa-eye' : 'fa-eye-slash') ?>"></i>
                                    </button>
<?php
                    } else {
?>
                                    <span class="btn btn-sm disabled <?php echo ($page->getMeta('visible') > 0 ? 'btn-success' : 'btn-default') ?>" title="Vous n'avez pas les droits pour exécuter cette action" style="cursor:not-allowed;">
                                        <i class="fa <?php echo ($page->getMeta('visible') > 0 ? 'fa-eye' : 'fa-eye-slash') ?>"></i>
                                    </span>

<?php
                    }
                }
            }else {
                if (count($this->versions) > 1) {
?>
                                <a href="" class="openlang-trad btn btn-sm btn-danger" title="Non traduit"><i class="fa fa-globe"></i></a>
<?php
                }
            }
?>
                            </div>
<?php
        }
?>
                        </div>
<?php
    }

    foreach ($this->pages as $page) {
?>
                        <div class="langue" id="langue_<?php echo $page->getMeta('id_version'); ?>" style="<?php if ($page->getMeta('id_version') != BACK_ID_VERSION && count($this->pages) > 1) { echo ' display:none;'; } ?>">
<?php
        if (count($this->versions) > 1) {
?>
                            <div style="margin-top:0" class="clearin"></div>

                            <div>
                                <select class="compareversion-other form-control" style="display:block;">
<?php
            foreach ($this->versions as $id_version => $version) {
                if ($id_version != $page->getMeta('id_version')) {
?>
                                    <option value="<?php echo $id_version . '|' . strtolower($version['suf']); ?>"><?php echo $version['nom']; ?></option>
<?php
                }
            }
?>
                                </select>
                                <button class="btn btn-sm btn compareversion-submit" style="margin-right: 10px;margin-left: 5px;"><i class="icon-resize-small"></i> Comparer</button>
                                <button class="btn btn-sm btn compareversion-hide" style=""><i class="icon-remove"></i> Cacher</button>
                            </div>
<?php
        }
?>
                            <div style="margin-top:0" class="clearin"></div>
<?php
        if (isset($this->redirections[$page->getMeta('id_version')])) {
            $redirections = $this->redirections[$page->getMeta('id_version')];
        } else {
            $redirections = array();
        }
        if (isset($this->authors[$page->getMeta('id_version')])) {
            $authors = $this->authors[$page->getMeta('id_version')];
        } else {
            $authors = array();
        }
        echo $page->getForm('back/page/save.html', 'back/page/liste.html', $redirections, $authors);
?>
                        </div>
<?php
    }

    if (isset($_GET['popup']) && $_GET['popup'] == 'more') {
        $this->add('template/pagedialog');
?>

<?php
    }
    $this->add('template/cropdialog');
?>
                        </div>