<?php
    if (isset($this->label)) {
?>
                <h1><?php echo $this->label; ?></h1>
<?php
    } else {
?>
                <h1>Liste des pages</h1>
<?php
    }

    $this
        ->add('breadcrumbs')
        ->add('template/button')
    ;
?>
                        <div class="cb"></div>
                        <hr />
<?php
    foreach ($this->pagesGroup as $keyGroup => $group) {
        /**
         * Si on affiche les pages par type de gabarits
         */
        if (isset($this->gabaritByGroup) && $this->gabaritByGroup) {
            if ($this->gabaritByGroup === true
                || (is_array($this->gabaritByGroup) && in_array($this->gabarits[$keyGroup]['id'], $this->gabaritByGroup))
            ) {
                $this->gabarits[$keyGroup]['group'] = true;
?>
                        <fieldset id="gab_page_6" class="sort-elmt">
                            <legend class="solire-js-toggle" title="<?php echo $this->gabarits[$keyGroup]['label']; ?>  ">
                                <?php echo $this->gabarits[$keyGroup]['label']; ?>
                            </legend>
<?php
            }
            $this->pages = $group;
        }
?>
                        <div class="sort-box" <?php echo isset($this->gabarits[$keyGroup]['group']) && $this->gabarits[$keyGroup]['group'] ? 'style="display:none;margin-left:30px;"' : ''; ?>>
<?php
    $this->add('template/page_list');
?>
                        </div>
<?php
        /**
         * Si on affiche les pages par type de gabarits
         */
        if ($this->gabaritByGroup === true
            || (is_array($this->gabaritByGroup) && in_array($this->gabarits[$keyGroup]['id'], $this->gabaritByGroup))
        ) {
?>
                    </fieldset>
<?php
        }
    }
?>
