<?php
    if (isset($this->label)) {
?>
                <h1><?php echo $this->label; ?></h1>
<?php
    } else {
?>
                <h1>Liste des pages</h1>
<?php
    }

    $this
        ->add('breadcrumbs')
        ->add('template/button')
    ;
?>
                        <div class="cb"></div>
                        <hr />
<?php
    foreach ($this->pagesGroup as $keyGroup => $group) {
        /**
         * Si on affiche les pages par type de gabarits
         */
        if (isset($this->gabaritByGroup) && $this->gabaritByGroup) {
?>
                        <fieldset id="gab_page_6" class="sort-elmt">
                            <legend title="<?php echo $this->gabarits[$keyGroup]['label']; ?>  ">
                                <?php echo $this->gabarits[$keyGroup]['label']; ?>
                            </legend>
<?php
            $this->pages = $group;
        }
?>
                        <div class="sort-box" <?php echo isset($this->gabaritByGroup) && $this->gabaritByGroup ? 'style="display:none;"' : ''; ?>>
<?php
    $this->add('template/page_list');
?>
                        </div>
<?php
        /**
         * Si on affiche les pages par type de gabarits
         */
        if (isset($this->gabaritByGroup) && $this->gabaritByGroup) {
?>
                    </fieldset>
<?php
        }
    }
?>
