<!doctype html public "-//W3C//DTD HTML 4.0//EN">
<!--[if !IE]><!-->
<html>
    <!--<![endif]-->
    <!--[if IE]>
    <html class="error">
    <![endif]-->

    <head>
        <title>Connexion</title>
        <meta name="ROBOTS" content="noindex, nofollow" />
        <meta name="GOOGLEBOT" content="noindex, nofollow" />

        <base href="<?php echo $this->url; ?>" />

        <link type="text/css" rel="stylesheet" media="screen" href="http://www.solire.fr/style_solire_fw/css/back/newstyle-1.1.css" />
        <link rel="stylesheet" href="app/back/css/sticky.css" type="text/css" media="screen" title="" charset="utf-8" />
        <link rel="stylesheet" href="app/back/css/bootstrap/bootstrap.min.css?1371827188" type="text/css" media="screen" />
        <link rel="stylesheet" href="app/back/css/bootstrap/bootstrap-responsive.min.css?1371473949" type="text/css" media="screen" />
        <link rel="stylesheet" href="app/back/css/newstyle-1.3.css" type="text/css" media="screen" />
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <style>
            .error form {
                display: none;
            }

            .error-message {
                display: none;
            }

            .error .error-message {
                display: block;
            }
            @font-face {
                font-family: 'FontomasCustomRegular';
                src: url('app/back/font/fontomas-webfont.eot');
                src: url('app/back/font/fontomas-webfont.eot?#iefix') format('embedded-opentype'),
                    url('app/back/font/fontomas-webfont.woff') format('woff'),
                    url('app/back/font/fontomas-webfont.ttf') format('truetype'),
                    url('app/back/font/fontomas-webfont.svg#FontomasCustomRegular') format('svg');
                font-weight: normal;
                font-style: normal;
            }


            [data-icon]:after {
                color: #888;
                content: attr(data-icon);
                font-family: 'FontomasCustomRegular';
                left: 8px;
                position: absolute;
                top: 16px;
                width: 30px;
            }

            form label {
                position: relative;
                width: 20px;
            }
            form input.mini {
                margin-top: 5px;
                width: 180px;
                padding: 3px 0px 3px 32px;
                -webkit-transition: width 1s ease;
                -moz-transition: width 1s ease;
                -o-transition: width 1s ease;
                -ms-transition: width 1s ease;
                transition: width 1s ease;
            }

            form input.mini:focus {
                width: 220px;
            }

            input:-moz-placeholder {
                color: #BEBEBE;
                width: 130px;
                font-style: italic;
            }
            input:hover {
                color: #666666;
            }
            input:focus {
                color: #666666;
            }

            .top-right, .top-left {
                top: -3px;
            }
            .btn {
                margin-left: 38px;
                margin-top: 0px;
                margin-bottom: 10px;
                position: relative;
            }

        </style>
    </head>
    <body style="background:#efefef;">
    <section>

        <article style="position: relative;margin-top:15%; margin-right:auto; margin-left:auto; width:356px; padding:20px;box-shadow:3px 2px 5px #BFBFBF">
<?php
    if ($this->emailSent) {
?>
            <p>Pour obtenir votre nouveau mot de passe, veuillez vérifier votre compte email, un lien vous a été envoyé.</p>
<?php
    } else {
?>
            <form id="sign-in" method="post" action="back/sign/asknewpassword.html">
                <fieldset>
                    <legend><b>Mot de passe perdu</b></legend>
<?php
        if ($this->error) {
?>
                    <p style="color:red;">Cet email n'est pas lié à un compte administrateur.</p>
<?php
        }
?>
                    <div class="line">
                        <label data-icon="u" for="log"></label>
                        <input type="text" placeholder="Identifiant" name="log" id="log" class="form-controle form-oblig form-mix mini" size="50" maxlength="100" />
                    </div>

                    <div class="">
                        <button class="btn btn-success btn-small" type="submit"><i class="icon-ok"></i> Demander un nouveau mot de passe</button>
					</div>

                </fieldset>
            </form>
<?php
    }
?>
            <p style="color:#888; float:right; font-size:10px; margin-top:10px;">Outil de gestion de contenu développé par <img src="app/back/img/logo-solire-fw.png" title="Solire : agence web lyon" style="float: right; margin: -2px 0 0px 4px ; height:20px;"/></p>
            <div style="clear:both;"></div>
        </article>
    </section>
</body>
</html>
