<!doctype html public "-//W3C//DTD HTML 4.0//EN">
<!--[if !IE]><!-->
<html>
    <!--<![endif]-->
    <!--[if IE]>
    <html class="error">
    <![endif]-->

    <head>
        <title>Connexion</title>
        <meta name="ROBOTS" content="noindex, nofollow" />
        <meta name="GOOGLEBOT" content="noindex, nofollow" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="<?php echo $this->url; ?>" />

<?php
    echo $this->css->outputAll();
?>
        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>
    <body class="page-signin" data-amd="modules/page/signin">
        <section>

            <article>
                <div class="error-message">
                    <b>Module d'administration</b>
                    <br />
                    <br />
                    <p>
                        Pour votre confort et votre sécurité, merci de télécharger un navigateur récent et compatible :
                        <a href="http://www.mozilla-europe.org/fr/" target="_blank">Firefox</a>,
                        <a href="http://www.google.com/chrome" target="_blank">Google Chrome</a>
                    </p>
                </div>

                <form data-amd="modules/page/form" id="sign-in" method="post" action="<?php echo $this->action; ?>">
                    <fieldset>
                        <legend><b>Module d'administration</b></legend>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
                                <input name="log" id="log" class="form-control form-controle form-oblig form-mix" type="text" placeholder="Identifiant">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-key fa-fw"></i></span>
                                <input name="pwd" id="pwd" class="form-control form-controle form-oblig form-mix" type="password" placeholder="Mot de passe">
                            </div>
                        </div>
                        <button class="btn btn-success btn-block" type="submit"><i class="icon-ok"></i> Connexion</button>

                    </fieldset>
                </form>

                <p style="color:#888; float:right; font-size:10px; margin-top:10px;">Outil de gestion de contenu développé par
<?php
    echo $this->img->output('back/img/logo-solire-fw.png', [
        'title' => 'Solire : agence web lyon',
        'style' => 'float: right; margin: -2px 0 0 4px; height:20px;',
    ], true);
?>
                </p>
                <div style="clear:both;"></div>
            </article>
        </section>
    
        <?php echo $this->requireJs->outputAll(); ?>
        <?php echo $this->javascript->outputAll(); ?>
    </body>
</html>
