


<h1>Tableau de bord</h1>

<?php $this->add('breadcrumbs'); ?>

<!--<h2>Liens rapides</h2>

<?php
foreach ($this->pages as $idGabarit => $pagesGabarit) {
    if (!$pagesGabarit["gabarit"]["creable"])
        continue;
    ?>
                            <div class="btn-a btn-shortcut fl">
                                <a href="back/page/display.html?id_gabarit=<?php //echo $pagesGabarit["gabarit"]["id"] ?>" class="" title="">
                                    <img src="img/gray_dark/document_alt_stroke_24x32.png" alt="">
                                    <b>Créer un<?php //echo $pagesGabarit["gabarit"]["genre"] == "f" ? 'e' : '' ?> <?php //echo $pagesGabarit["gabarit"]["label"] ?></b>
                                </a>
                            </div>
    <?php
}
?>


<div class="cb"></div>

<hr>-->
<!--
<div id="columns">
    <ul id="column1" class="column">
        <?php if ($this->appConfig->get("introduction", "board")) {
            ?>
            <li class="widget gradient-green" id="intro">
                <div class="widget-head gradient-green">
                    <h3>Introduction</h3>
                </div>
                <div class="widget-content">
                    <p>
                        Le tableau de bord vous permet de visualiser les dernières pages éditées et créées par type de page. Vous pouvez réorganiser chaque bloc du tableau de bord, l'état de celui-ci sera sauvegardé pour votre utilisateur.
                    </p>
                </div>
            </li>

            <?php }
        ?>
        <li class="widget gradient-green"  id="resume">
            <div class="widget-head gradient-green">
                <h3>Résumé</h3>
            </div>
            <div class="widget-content">

                <?php
                $nbGab = 0;
                foreach ($this->pages as $idGabarit => $pagesGabarit) {
                    $nbGab++;
                    ?>
                    <div style="margin-top: 10px;">
                        <span class="number"><?php echo $pagesGabarit["gabarit"]["nbpages"] ?></span><?php echo $pagesGabarit["gabarit"]["label"] ?>
                    </div>
                    <?php
                    if ($nbGab != count($this->pages)) {
                        ?>
                        <hr>
                        <?php
                    } else {
                        ?>
                        <br />
                        <?php
                    }
                    ?>

                    <?php
                }
                ?>


            </div>
        </li>
    </ul>
    <ul id="column2" class="column">


    </ul>
    <ul id="column3" class="column"></ul>


</div>

<div class="cb"></div>
<hr />
-->
<?php echo $this->datatableRender; ?>

