antibruteforce:
  bantime: 900 # en seconde
  ignoreip:
    - 127.0.0.1
  filter:
    apache-denied:
      enabled: true
      maxretry: 5
      findtime: 60 # en seconde
      log:
        back_log:
          handler: MonologPDO
          table: monolog
          channel-column: channel
          datetime-column: FROM_UNIXTIME(time)
          ip-column: remoteip
          search-column: message
          channel: backUser
          failregex:
            - '%Connexion échouée%'