<table class="w580" border="0" cellpadding="0" cellspacing="0" width="580">
    <tbody>
    <tr>
        <td colspan="2" class="w580" width="580">
            <p class="article-title-2" align="left">Pour créer votre nouveau mot de passe, cliquez sur le lien : </p>

            <div class="article-content" align="center">
                <a href="<?php echo \Solire\Lib\Registry::get('basehref') . $this->url; ?>">"RÉGÉNÉRER MON MOT DE PASSE"</a>
            </div>
        </td>
    </tr>
    <tr>
        <td class="w580" height="10" width="580"></td>
    </tr>
    </tbody>
</table>
