# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: contenu
    itemsName: contenus
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: back/datatable/listdata.html?name=board
    requestMethod: POST
    separator: "~"
    dom: <"H"TClfr>t<"F"ip>
    defaultSort:
    - [0, asc]

source:
  name: doctrine
  conf:
    select:
      - p.titre
      - p.date_crea
      - p.date_modif
      - g.label

    from:
      name: gab_page
      alias: p

    innerJoin:
      -
        name: gab_gabarit
        alias: g
        'on': g.id = p.id_gabarit


## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    sort: 1|0
#    filter: 1|0
#    filterType: text, dateRange...
#    source: source expression (for example a column)
#    sourceFilter: source expression (for example a column)
#    sourceSort: source expression (for example a column)
#    ...

  titre:
    label: Titre
    filter: 1
    sort: 1
    source: p.titre

  label:
    label: Type de contenu
    filter: 1
    sort: 1
    source: g.titre

  date_crea:
    label: Créé
    filter: 1
    sort: 1
    source: p.date_crea

  date_modif:
    label: Édité
    filter: 1
    sort: 1
    source: p.date_modif