# -------------------------
# CONFIG

# Js Config
driver:
  name: dataTables
  conf:
    itemName: média
    itemsName: médias
    # masculin ou féminin
    # "e"|""
    itemGenre:
    requestUrl: back/mediadatatable/listdata.html?name=media
    requestMethod: POST
    separator: "~"
    defaultSort:
    - [1, desc]

source:
  name: doctrine
  conf:
    select:
      - m.rewriting
      - CONCAT(IF(m.id_gab_page = 0, CONCAT('temp-', m.id_temp), m.id_gab_page), '/', m.rewriting) fullpath
      - m.date_crea


    from:
      name: media_fichier
      alias: m

    group: m.id

## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    sort: 1|0
#    filter: 1|0
#    filterType: text, dateRange...
#    source: source expression (for example a column)
#    sourceFilter: source expression (for example a column)
#    sourceSort: source expression (for example a column)
#    ...

  fullpath:
    label: Rewriting
    filter: 1
    sort: 1
    source: fullpath
    format:
      class: Solire\Lib\Trieur\Format\Twig
      fileName: datatable/media/preview.html.twig

  date_crea:
    label: Date import
    filter: 1
    sort: 1
    source: m.date_crea
    driverFilterType: dateRange
    sourceFilterType: DateRange
    format:
      class: \Solire\Trieur\Format\Callback
      name:
        - Solire\Lib\Format\DateTime
        - relativeTime
      cell: timestampOrDate