# -------------------------
# CONFIG
title: Liste des redirections 301

# Js Config
driver:
  name: dataTables
  conf:
    itemName: redirection
    itemsName: redirections
    # masculin ou féminin
    # "e"|""
    itemGenre: e
    requestUrl: back/datatable/listdata.html?name=redirection
    requestMethod: POST
    separator: "~"
    defaultSort:
    - [1, desc]

source:
  name: doctrine
  conf:
    select:
      - r.id
      - r.old
      - r.new
      - r.id_version
      - r.id_api

    from:
      name: redirection
      alias: r

    where:
      - r.id_version = {%parameters:idVersion}
      - r.id_api = {%parameters:idApi}

## COLUMNS

columns:
#  columnName:
#    label: columnLabel
#    sort: 1|0
#    filter: 1|0
#    filterType: text, dateRange...
#    source: source expression (for example a column)
#    sourceFilter: source expression (for example a column)
#    sourceSort: source expression (for example a column)
#    ...

  old:
    label: Ancienne url
    filter: 1
    sort: 1
    source: r.old

  new:
    label: Nouvelle url
    filter: 1
    sort: 1
    source: r.new

  action:
    label: Action
    filter: 0
    sort: 0
    source: id
    format:
      class: Solire\Lib\Trieur\Format\Twig
      fileName: redirection/columns/action.html.twig