<?php
    if (isset($this->gabaritsBtn) && count($this->gabaritsBtn)) {
        foreach ($this->gabaritsBtn as $gabaritGroup) {
?>
                        <div style="float:left;">
<?php
            if (count($gabaritGroup["gabarit"]) > 1) {
                /**
                 *  Group
                 */
?>

                            <div style="margin-right: 10px;" class="btn-group">
                                <a href="#" data-toggle="dropdown" class="btn btn-success btn-small"> <?php echo $gabaritGroup['label'] ?></a>
                                <a href="#" data-toggle="dropdown" class="btn btn-success btn-small dropdown-toggle">
                                    <i style="padding:1px 0px 0px 0px;" class="icon-chevron-down icon-white"></i>
                                </a>
                                <ul class="dropdown-menu">
<?php
                foreach ($gabaritGroup["gabarit"] as $gabarit) {

                    if ($this->utilisateur->get("niveau") != "solire" && !$gabarit["creable"]) {
                        continue;
                    }
?>
                                    <li>
                                        <i></i> <a href="back/page/display.html?id_gabarit=<?php echo $gabarit['id'] ?>"><?php echo $gabarit['label'] ?></a>
                                    </li>
<?php
                }
?>
                                </ul>
                            </div>

<?php
            } else {
                /**
                 * Gabarit simple
                 */
?>
                            <a style="margin-right: 10px;" class="btn btn-small btn-success btn-crea" href="back/page/display.html?id_gabarit=<?php echo $gabaritGroup['gabarit'][0]['id'] ?>">
                                <?php echo $gabaritGroup['label'] . $gabaritGroup['gabarit'][0]["label"] ?>
                            </a>

<?php
            }
?>
                        </div>
<?php
        }
    }
?>
