<?php
    if (isset($this->gabaritsBtn) && count($this->gabaritsBtn)) {
        foreach ($this->gabaritsBtn as $gabaritGroup) {
?>
<?php
            if (count($gabaritGroup["gabarit"]) > 1) {
                /**
                 *  Group
                 */
?>

                            <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-success btn-sm"> 
                                    <?php echo $gabaritGroup['label'] ?>
                                </button>
                                <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
<?php
                foreach ($gabaritGroup["gabarit"] as $gabarit) {

                    if ($this->utilisateur->get("niveau") != "solire" && !$gabarit["creable"]) {
                        continue;
                    }
?>
                                    <li>
                                        <i></i> <a href="back/page/display.html?id_gabarit=<?php echo $gabarit['id'] ?>"><?php echo $gabarit['label'] ?></a>
                                    </li>
<?php
                }
?>
                                </ul>
                            </div>

<?php
            } else {
                /**
                 * Gabarit simple
                 */
?>
                            <a class="btn btn-sm btn-success btn-crea" href="back/page/display.html?id_gabarit=<?php echo $gabaritGroup['gabarit'][0]['id'] ?>">
                                <?php echo $gabaritGroup['label'] . $gabaritGroup['gabarit'][0]["label"] ?>
                            </a>

<?php
            }
?>
<?php
        }
    }
?>
