<div class="modal hide fade" style="display: none;" id="modalCrop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Recadrer</h3>
    </div>

    <div class="modal-body">
        <table style="width:100%" class="border-none" border="0">
            <tr>
                <td style="border:1px solid #CFCFCF;background: black"></td>

                <td style="vertical-align:top;">

                    <form class="form-crop form-horizontal" action="media/crop.html" method="post" style="width: 325px;">
                        <fieldset class="img-info">
                            <legend>Information</legend>
                            <div>
                                <dl style="display: none" class="dl-horizontal expected-width">
                                    <dt style="width: 180px;">Largeur minimale attendue</dt>
                                    <dd style="margin-left: 190px;"><span id="minwidthShow"></span>px</dd>
                                </dl>
                                <dl style="display: none" class="dl-horizontal expected-height">
                                    <dt style="width: 180px;">Hauteur minimale attendue</dt>
                                    <dd style="margin-left: 190px;"><span id="minheightShow"></span>px</dd>
                                </dl>
                            </div>
                        </fieldset>

                        <fieldset>
                            <legend>Sélection</legend>
                            <div>
                                <div class="control-group">
                                    <label class="control-label" for="wShow">Largeur</label>
                                    <div class="controls">
                                        <input type="text" style="width: 60px" class="wShow spinner" id="wShow" placeholder="Largeur" value="" />
                                    </div>
                                </div>
                                <div class="control-group">
                                    <label class="control-label" for="hShow">Hauteur</label>
                                    <div class="controls">
                                        <input type="text" style="width: 60px" class="hShow spinner" id="hShow" placeholder="Hauteur" value="" />
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <fieldset>
                            <legend>Enregistrement</legend>
                            <div>
                                <div class="control-group" style="display:none;">
                                    <label class="radio expected-height">
                                        <input type="radio" value="height" class="" name="force-width">Respecter la hauteur minimum
                                    </label>
                                    <label class="radio expected-width">
                                        <input type="radio" value="width" class="" name="force-width">Respecter la largeur minimum
                                    </label>
                                    <label class="radio expected-width-height">
                                        <input type="radio" value="width-height" class="" name="force-width">Respecter la hauteur et la largeur minimum
                                    </label>

                                    <label class="radio force-selection">
                                        <input type="radio"  value="1" name="force-width" checked="checked">Forcer la taille en fonction de la sélection
                                    </label>
                                </div>

                                <div class="control-group radio">
                                    <label class="">Nom de l'image</label>
                                    <input type="text" id="image-name" name="image-name" class="input-xlarge" placeholder="Nom de l'image" value="" />
                                    <input type="hidden" id="image-extension" name="image-extension"  />
                                </div>
                                <div class="control-group radio">
                                    <label class="">Texte alternatif</label>
                                    <input type="text" id="image-alt" name="image-alt" class="input-xlarge" placeholder="Légende de l'image" value="" />
                                </div>
                            </div>

                            <input type="hidden" id="filepath" name="filepath" />
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <input type="hidden" id="minwidth" name="minwidth" />
                            <input type="hidden" id="minheight" name="minheight" />
                        </fieldset>
                    </form>
                </td>
            </tr>
        </table>
    </div>

    <div class="modal-footer">
        <button class="btn btn-default btn-small" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Annuler</button>
        <button class="btn btn-small btn-primary form-crop-submit"><i class="icon-fullscreen"></i> Valider</button>
    </div>

</div>