<div id="modalMore" class="hidden" >
    <div class="modal-header">
        <button type="button" class="close soModalDefaultClose" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Que voulez-vous faire ?</h3>
    </div>

    <div class="modal-body row">
        <div class="col-md-12">
            <div class="line form-group">
                <label class="col-sm-3 control-label">
                    Gérer la visibité
                </label>
                <div class="col-sm-8">

                    <?php
                    $page = $this->pages[BACK_ID_VERSION];

                    if ($page->getMeta("rewriting") != '') {
                    if ($this->utilisateur->get("niveau") == "solire"
                    || ($page->makeHidden && $page->getMeta('visible') == 1)
                    || ($page->makeVisible && $page->getMeta('visible') == 0)
                    ) {
                    ?>
                    <div class="btn-group">
                        <a title="<?php echo $version['nom']; ?>" class="btn btn-default btn-sm">
                            <img src="public/default/back/img/flags/png/<?php echo strtolower($this->mainVersions[$page->getMeta("id_version")]["suf"]); ?>.png" alt="<?php echo $this->mainVersions[$page->getMeta("id_version")]["nom"]; ?>" />
                        </a>

                        <button
                            class="btn btn-sm <?php echo ($page->getMeta('visible') > 0 ? 'btn-success' : 'btn-default') ?> exec-onclick-ajax"
                            data-url="back/page/visible.html"
                            data-id="<?php echo $page->getMeta('id'); ?>"
                            data-id_version="<?php echo BACK_ID_VERSION; ?>"
                            data-visible="<?php echo $page->getMeta('visible'); ?>"
                            title="Rendre '<?php echo $page->getMeta('titre'); ?>' <?php echo ($page->getMeta('visible') > 0 ? 'invisible' : 'visible' ) ?> sur le site">

                            <i class="fa <?php echo ($page->getMeta('visible') > 0 ? 'fa-eye' : 'fa-eye-slash') ?>"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php
        }
        }
        ?>

        <div class="col-md-12">
            <div class="line form-group">
                <label class="col-sm-3 control-label">
                    Éditer une autre page
                </label>
                <div class="col-sm-8">
                    <input data-amd="modules/helper/search" data-url="back/page/livesearch.html" type="text" placeholder="Recherche" class="form-control search live-search ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="line form-group">
                <label class="col-sm-3 control-label">
                    Créer un nouveau contenu
                </label>
                <div class="col-md-6">
                    <?php $this->add('template/button'); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button class="btn btn-primary btn-sm" onclick="var link = $('.back-to-list').attr('href');window.location = link;">Retour à la liste des pages</button>
        <?php
        $page = $this->pages[BACK_ID_VERSION];
        if ($page->getGabarit()->getView()) {
            ?>
            <a class="btn btn-primary  btn-sm"  href="<?php echo $this->pagePath; ?>" target="_blank">Consulter cette page dans le site</a>
            <?php
        }
        ?>
        <button class="btn btn-primary  btn-sm" data-dismiss="modal" aria-hidden="true">Reprendre l'édition de cette page</button>
    </div>
</div>