<?php
        if (count($this->pages) > 0) {
            foreach ($this->pages as $page) {
                $gabarit = $this->gabarits[$page->getMeta('id_gabarit')];

                $htmlUrl = '';
                if (isset($this->urlRedir)) {
                    $htmlUrl .= ' data-url="' . $this->urlRedir . $page->getMeta('id') . '"';
                }

                if (isset($this->urlAjax)) {
                    $urlAjax = $this->urlAjax;
                } else {
                    $urlAjax = 'back/page/children.html';
                }

                if ((isset($this->noChild) && $this->noChild === true)
                    || $page->getMeta('nbre_enfants') == 0
                ) {
                    $class = ' class="noChild"';
                } else {
                    $class = ' class="solire-js-toggle"';
                }
?>
                            <fieldset data-titre="<?php echo $page->getMeta('titre'); ?>" style="<?php echo isset($this->margin) ? 'margin-left:30px;' : '' ; ?>" class="<?php if ($this->utilisateur->get('niveau') == 'solire' || $gabarit['sortable']) { ?>sort-elmt<?php } ?>" id="gab_page_<?php echo $page->getMeta('id'); ?>">
                                <legend<?php echo $htmlUrl; ?> data-ajax="<?php echo $urlAjax; ?>" title="<?php echo $page->getMeta('rewriting') ?>"<?php echo $class; ?>>
<?php
                $link = false;
                if ($page->getMeta('nbre_enfants') > 0
                    && (isset($this->noChild) && $this->noChild === false
                        || !isset($this->noChild)
                    )
                ) {
?>
                                    <i class="fa fa-folder"></i>
<?php
                } elseif (($this->utilisateur->get('niveau') == 'solire' || $gabarit['editable'])) {
                    $link = true;
?>
                                    <a href="back/page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>" title="Modifier '<?php echo $page->getMeta('titre'); ?>'"><i class="fa fa-file"></i>
<?php
                }
?>
                                    <?php echo $page->getMeta('titre'); ?>
                                    <br />
<?php
                if ($page->getMeta('date_modif') != '0000-00-00 00:00:00'
                    && $page->getMeta('rewriting') != ''
                ) {
?>
                                    <span class="board-human-time" style="color: inherit">Dernière édition <?php echo $page->getMeta('date_modif') != '0000-00-00 00:00:00' ? Slrfw\Format\DateTime::relativeTime($page->getMeta('date_modif'), true) : ''; ?></span>
<?php
                }
?>
                                    <span class="page-info">
<?php
                if ($page->getMeta('id_gabarit') != 1
                    && $page->getMeta('id_gabarit') != 2
                    && (isset($this->noType) && $this->noType === false || !isset($this->noType))
                ) {

                    if ($page->getMeta('date_modif') != '0000-00-00 00:00:00'
                        && $page->getMeta('rewriting') != ''
                    ) {
?>
                                        |
<?php
                    }
?>
                                        <i>Type : <?php echo $gabarit['label'] ?></i>
<?php
                }
                $nbChild = $page->getMeta('nbre_enfants');
                if (!empty($nbChild)) {
                $displayChild = $page->getMeta('aff_enfants');
                    if (empty($displayChild)) {
                        $displayChild = $page->getMeta('nbre_enfants');
                    }
?>
                                        | <i><span class="page-nbre-enfants"><?php echo $displayChild; ?> </span><?php echo $this->childName; ?></i>
<?php
                }
?>
                                    </span>
<?php
            if ($link) {
?>
                                    </a>
<?php
            }
?>
                                </legend>

                                <div class="sort-box" style="display:none;"></div>

                                <div style="position: relative" class="line cat-modif">
                                    <div style="float:left; margin-left:8px;">
                                        <div class="btn-toolbar">
                                            <div class="btn-group">
<?php
                if ($page->getMeta('id_gabarit') == 1
                    || $page->getMeta('id_gabarit') == 2
                ) {
?>
                                                <a href="back/page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>" class="btn btn-small btn-info" title="Modifier '<?php echo $page->getMeta('titre'); ?>'"><i class="icon-pencil"></i></a>
<?php
                } else {
?>
<?php
                    if (count($this->pages) > 1
                        && ($this->utilisateur->get('niveau') == 'solire'
                            || $page->sortable
                        )
                    ) {
?>
                                                <a href="#" class="btn btn-info btn-small sort-move" title="Déplacer '<?php echo $page->getMeta('titre'); ?>'"><i class="icon-retweet"></i></a>
<?php
                    }
                    if ($this->utilisateur->get('niveau') == 'solire'
                        || $gabarit['editable']
                    ) {
?>
                                                <a href="back/page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>" class="btn btn-small btn-info" title="Modifier '<?php echo $page->getMeta('titre'); ?>'"><i class="icon-pencil"></i></a>
<?php
                    }

                    if ($page->getMeta('rewriting') != ''
                        && ($this->utilisateur->get("niveau") == "solire"
                            || $gabarit['make_hidden'] > 0
                            || $page->getMeta('visible') == 0
                        )
                    ) {
                        if ((
                                ($page->makeHidden && $page->getMeta('visible') == 1)
                            || ($page->makeVisible && $page->getMeta('visible') == 0)
                            )
                            && $page->getMeta('rewriting') != ''
                        ) {
?>
                                                <a class="btn btn-small <?php echo ($page->getMeta('visible') > 0 ? 'btn-success' : 'btn-default') ?> visible-lang"  title="Rendre '<?php echo $page->getMeta('titre'); ?>' <?php echo ($page->getMeta('visible') > 0 ? 'invisible' : 'visible' ) ?> sur le site">
                                                    <input type="checkbox" value="<?php echo $page->getMeta('id'); ?>|<?php echo $page->getMeta('id_version'); ?>" style="display:none;" class="visible-lang-<?php echo $page->getMeta('id'); ?>-<?php echo $page->getMeta('id_version'); ?>" <?php echo ($page->getMeta('visible') > 0 ? ' checked="checked"' : '') ?> />
                                                    <i class="<?php echo ($page->getMeta('visible') > 0 ? 'icon-eye-open' : 'icon-eye-close') ?>"></i>
                                                </a>

<?php
                        } else {
?>
                                                <span class="btn btn-small disabled <?php echo ($page->getMeta('visible') > 0 ? 'btn-success' : 'btn-default') ?>" title="Vous n'avez pas les droits pour exécuter cette action" style="cursor:not-allowed;">
                                                    <i class="<?php echo ($page->getMeta('visible') > 0 ? 'icon-eye-open' : 'icon-eye-close') ?>"></i>
                                                </span>

<?php
                        }
                    }

                    if ($page->getMeta('rewriting') == '') {
?>
                                                <a href="back/page/display.html?id_gab_page=<?php echo $page->getMeta('id'); ?>" class="btn btn-small btn-danger" title="Non traduit"><i class="icon-globe"></i></a>
<?php
                    }

                    if (($this->utilisateur->get('niveau') == 'solire' || $page->deletable)
                        && $page->getMeta('nbre_enfants') == 0
                    ) {
?>
                                                <a href="#" style="display:<?php echo $page->getMeta('nbre_enfants') > 0 ? 'none' : 'inline-block'; ?>;" class="btn btn-small btn-warning supprimer" title="Supprimer '<?php echo $page->getMeta('titre'); ?>'"><i class="icon-trash"></i></a>
<?php
                    }
                }
?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
<?php
            }
        } else {
?>
                            <p>Aucune page</p>
<?php
        }
?>
