                        <ol class="breadcrumb">
<?php
    foreach ($this->breadCrumbs as $iLink => $link) {

        if ($iLink == count($this->breadCrumbs) - 1 || !isset($link["url"])) {
?>
                            <li class="<?php echo $iLink == count($this->breadCrumbs) - 1 ? 'active' : ''; ?>">
                                <?php echo $link["label"]; ?>
                            </li>
<?php
        } else {
?>
                            <li>
                                <a href="back/<?php echo $link["url"]; ?>"><?php echo $link["label"]; ?></a>
                            </li>
<?php
        }
    }
?>
                        </ol>
