                        <ul class="xbreadcrumbs cf" id="breadcrumbs" style="">
<?php
    foreach ($this->breadCrumbs as $iLink => $link) {

        if ($iLink == count($this->breadCrumbs) - 1 || !isset($link["url"])) {
?>
                            <li class="<?php echo $iLink == count($this->breadCrumbs) - 1 ? 'current' : 'parent'; ?>">
                                <a class="vam" <?php echo $iLink == count($this->breadCrumbs) - 1 ? '' : 'style="color: #222222"'; ?>><?php echo $link["label"]; ?></a>
                            </li>
<?php
        }
        else {
?>
                            <li class="parent">
                                <a class="vam" href="back/<?php echo $link["url"]; ?>"><?php echo $link["label"]; ?></a>
                            </li>
<?php
        }
    }
?>
                        </ul>
