<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; text/css; charset=utf-8" />

        <title>Module de gestion du site <?php echo $this->site; ?>
<?php
    if (isset($this->breadCrumbs) && count($this->breadCrumbs) > 1) {
?>
                |
<?php
        foreach ($this->breadCrumbs as $iLink => $link) {
            if ($iLink == 0) {
                continue;
            }

            if ($iLink == count($this->breadCrumbs) - 1) {
?>
                        <?php echo $link["label"]; ?>
<?php
            }
            else {
?>
                        <?php echo $link["label"]; ?> >
<?php
            }
?>

<?php
        }
    }
?>
        </title>
        <meta name="publisher" content="SOLIRE" />
        <meta name="robots" content="noindex, nofollow" />
        <meta name="googlebot" content="noindex, nofollow" />

        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
        <meta name="viewport" content="width=1220; user-scalable=yes" />

        <base href="<?php echo $this->url; ?>" />
<?php
    echo $this->css->outputAll();
?>
    </head>

    <body>
        <?php $this->add('menu'); ?>
        <div class="container">

<?php
    echo $this->content();
?>
        </div>
        <footer class="footer container">
            <p class="license">
                <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/fr/"  target="_blank"><img class="license-logo" alt="Licence Creative Commons" src="http://i.creativecommons.org/l/by-nc/3.0/fr/80x15.png" /></a><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">L'outil de gestion de contenu </span> de 
                <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.solire.fr" property="cc:attributionName" rel="cc:attributionURL" target="_blank">
<?php
echo $this->img->output('back/img/logo-solire-fw.png', [
    'title' => 'Solire : agence web lyon',
    'style' => 'margin: -1px 0 0px 4px ; height:20px;',
], true);
?>                              
                </a> est mis à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/fr/" target="_blank">licence Creative Commons Attribution - Pas d’Utilisation Commerciale 3.0 France</a>.
            </p>
        </footer>
        <?php
    echo $this->requireJs->outputAll();
    echo $this->javascript->outputAll();
?>
    </body>

</html>
