<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle nav_condensed" href="#">
            <img alt="<?php echo $this->mainVersions[BACK_ID_VERSION]['nom'] ?>" src="public/default/back/img/flags/all/24/<?php echo strtolower($this->mainVersions[BACK_ID_VERSION]['suf']) ?>.png" />
            <i class="fa fa-caret-down"></i>
        </a>

        <ul class="dropdown-menu">
            <?php
            foreach ($this->mainVersions as $version) {
                ?>
                <li>
                    <a style="cursor:pointer;" onclick="$.cookie('back_id_version', <?php echo $version['id'] ?>, {path: '/'}); document.location.href = document.location.href; return false;">
                        <img style="width: 16px; height: 16px;display: block;float: left;margin-top: 1px;" alt="" src="public/default/back/img/flags/all/16/<?php echo strtolower($version['suf']) ?>.png" />&nbsp;&nbsp;<?php echo $version['nom'] ?>
                    </a>
                </li>
                <?php
            }
            ?>
        </ul>
    </li>
    <li class="dropdown<?php echo $this->controller == 'back/user' && $this->action == 'start' ? ' gradient-blue text-light-white' : ''; ?>">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu">
            <li class="<?php echo $this->controller == 'back/user' && $this->action == 'start' ? 'active' : ''; ?>">
                <a href="back/user/start.html"><b>Mon profil (<?php echo $this->utilisateur->get("nom"); ?> <?php echo $this->utilisateur->get("prenom"); ?>)</b></a></li>
            <li class="divider"></li>
            <li><a href="back/sign/signout.html"><b>Déconnexion</b></a></li>
        </ul>
    </li>
</ul>
<form class="navbar-form navbar-right" role="search">
    <div class="form-group">
        <input data-amd="modules/helper/search" data-url="back/page/livesearch.html" type="text" class="form-control live-search" placeholder="Recherche">
    </div>
</form>