            <div class="nav-collapse">
              <nav>
                <ul class="nav">
<?php
  $mobile = false;
  if (count($this->apis) > 1) {
?>
                  <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                      <?php echo $this->api["label"]; ?> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
<?php
    $prefix = "../";
    if ($this->api["id"] == 1) {
      $prefix = "./";
    }

    foreach ($this->apis as $idApi => $api) {
      if ($api["name"] == "mobile") {
        $mobile = true;
      }
?>
                      <li>
                        <a href="./back/" style="font-weight:bold;" onclick="$.cookie('api', '<?php echo $api['name']; ?>', {path : '/'});">
                          <span class="api-selected" style="padding: 10px 10px 11px 14px;display:inline-block"><?php echo $api["label"]; ?></span>
                        </a>
                      </li>
<?php
    }
?>
                    </ul>
                  </li>

                  <li class="divider-vertical divider-simple hidden-phone hidden-tablet">&nbsp;</li>
<?php
  }

  $this->add('menu-' . $this->api['id']);
?>
                </ul>
              </nav>
            </div>
