<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="./back/"><?php echo $this->site; ?></a>
            </div>

            <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
<?php
    $this->add('menuRight');
    $this->add('menuLeft');
?>
            </div>
        </div>
    </nav>
</header>
