    <header>
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="back/" class="brand" style="padding:16px 7px 16px 23px; background:url(public/default/back/img/gray_dark/home_16x16.png) no-repeat center left; content: ">
              <?php echo $this->site; ?>
            </a>
<?php
  $this->add('menuRight');
  $this->add('menuLeft');
?>
            <div class="cb"></div>
          </div>
        </div>
      </div>
    </header>
